yaml
name: CI/CD Pipeline
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Comprobar el código
uses: actions/checkout@v2
- name: Indicar Python
uses: actions/setup-python@v2
with:
python-version: '3.x'
- name: Instalar dependencias
run: pip install -r requirements.txt
- name: Hacer las pruebas
run: pytest
# hasta aquí es donde vamos a hacer
- name: Desplegar a pre-producción
if: success()
run: |
echo "Deploying to staging..."
# Aquí estarán los comandos necesarios para desplegar
- name: Desplegar to producción
if: success() && github.ref == 'refs/heads/main'
run: |
echo "Deploying to production..."
# Aquí estarán los comandos necesarios para desplegar
